## Hubs
## FIXME: we may want spoke/log volumes mounted in from host for efficiency (skip aufs layer)
version: '2'
services:
  'hub_01':
    build: ./hub
    depends_on: 
      - zk_01
      - zk_02
      - zk_03
    volumes:
      - conf:/opt/hub/conf/
  'hub_02':
    build: ./hub
    depends_on: 
      - zk_01
      - zk_02
      - zk_03
    volumes:
      - conf:/opt/hub/conf/
  'hub_03':
    build: ./hub
    depends_on: 
      - zk_01
      - zk_02
      - zk_03
    volumes:
      - conf:/opt/hub/conf/
  
## Zookeepers
  zk_01:
    build: 
      context: ./zk
      args: 
        myid: '1'
  zk_02:
    build:
      context: ./zk
      args: 
        myid: '2'
  zk_03:
    build: 
      context: ./zk
      args: 
        myid: '3'
## Haproxy
  haproxy:
    build: 
      context: haproxy
    depends_on:
      - 'hub_01'
      - 'hub_02'
      - 'hub_03'
    ports:
      - "80:80"

## REQUIRES PUTTING CONF INTO A VOLUME CALLED (/var/lib/docker/volumes/hub_conf/_data/) HUB_CONF 
volumes:
  conf:
    driver: local
