## This file holds the context data for the DEV environment to fill template files.
## The syntax is:
##
## relative/path/to/file :
##     _template: tplFile.jinja
##     parameter_name : parameter_value
##     parameter2 :
##         - item1
##         - item2
##
## The file should be in yaml syntax, with one top-level array for each template file.
## There should be a corresponding template file in triforce/tpl/ written in the Jinja templating language
## for each top-level item.
##
conf/hub.properties :
    _template : hub.properties.jinja

    app :
        name : "hub"
        environment : "dev"

    backing :
        store : "aws"

    aws :
        protocol : "HTTP"

    dynamo :
        endpoint : "dynamodb.us-east-1.amazonaws.com"
        table_creation_wait_minutes : 10

    graphite :
        hosts : "svcsmon.cloud-east.dev:2003"

    ## This is temporary
    zookeeper :
        connection : "deihub-01.cloud-east.dev:2181,deihub-02.cloud-east.dev:2181,deihub-03.cloud-east.dev:2181"


conf/hazelcast.conf.xml :
    _template : hazelcast.conf.xml.jinja
    cluster_hosts :
        - "hub-01.cloud-east.dev"
        - "hub-02.cloud-east.dev"
        - "hub-03.cloud-east.dev"

bin/start.sh :
  _template : start.sh.jinja
  max_heap : "450m"
  min_heap : "256m"
  min_new : "100m"

##This is ignored for now
conf/zoo.cfg :
    _template : zoo.cfg.jinja
    dataDir : "/home/hub/hub/mnt/zookeeper/"
    dataLogDir : "/home/hub/hub/mnt/zookeeper/"
    server :
      1 : "hub-01.cloud-east.dev:2888:3888"
      2 : "hub-02.cloud-east.dev:2888:3888"
      3 : "hub-03.cloud-east.dev:2888:3888"

