## This file holds the context data for the prod environment to fill template files.
## The syntax is:
##
## relative/path/to/file :
##     _template: tplFile.jinja
##     parameter_name : parameter_value
##     parameter2 :
##         - item1
##         - item2
##
## The file should be in yaml syntax, with one top-level array for each template file.
## There should be a corresponding template file in triforce/tpl/ written in the Jinja templating language
## for each top-level item.
##
conf/hub.properties :
    _template : hub.properties.jinja

    app :
        name : "hub"
        environment : "prod"

    backing :
        store : "aws"

    aws :
        protocol : "HTTP"

    dynamo :
        endpoint : "dynamodb.us-east-1.amazonaws.com"
        table_creation_wait_minutes : 10

    s3 :
      content_backoff_wait : 1000
      content_backoff_times : 6
      environment : "prod-east1.flightstats.com"

    graphite :
        hosts : "svcsmon.cloud-east.prod:2003"

    zookeeper :
        connection : "hub-zk-01.cloud-east.prod:2181,hub-zk-02.cloud-east.prod:2181,hub-zk-03.cloud-east.prod:2181"


conf/hazelcast.conf.xml :
    _template : hazelcast.conf.xml.jinja
    cluster_hosts :
        - "hub-01.cloud-east.prod"
        - "hub-02.cloud-east.prod"
        - "hub-03.cloud-east.prod"

bin/start.sh :
  _template : start.sh.jinja
  max_heap : "450m"
  min_heap : "256m"
  min_new : "100m"

conf/logback.xml :
    _template : logback.xml.jinja


