## This file holds the context data for the DEV environment to fill template files.
## The syntax is:
##
## relative/path/to/file :
##     _template: tplFile.jinja
##     parameter_name : parameter_value
##     parameter2 :
##         - item1
##         - item2
##
## The file should be in yaml syntax, with one top-level array for each template file.
## There should be a corresponding template file in triforce/tpl/ written in the Jinja templating language
## for each top-level item.
##
conf/hub.properties :
    _template : hub.properties.jinja

    app :
        name : "hub-v2"
        environment : "prod"
        encrypted : false
        shutdown_delay_seconds : 15
        shutdown_wait_seconds : 60
        url : "http://hub-v2.svc.prod/"

    verification :
        one: 15
        two: 30
        three: 45

    backing :
        store : "aws"

    aws :
        protocol : "HTTP"

    dynamo :
        endpoint : "dynamodb.us-east-1.amazonaws.com"
        table_creation_wait_minutes : 10

    s3 :
      environment : "prod-east1.flightstats.com"
      endpoint : "s3-external-1.amazonaws.com"
      maxQueryItems : 1000
      writeQueueSize : 2000
      writeQueueThreads : 20
      dropSomeWrites : false

    audit :
      threads: 0
      queue: 0

    hosted_graphite :
        enable: true
        registerJvmMetrics : false
        host : "carbon.hostedgraphite.com"
        port : 2003
        prefix : cb165ed6-4336-4cc6-91ff-cfe1d04cebd6.hubv2.prod

    zookeeper :
        connection : "hub-zk-01.cloud-east.prod:2181,hub-zk-02.cloud-east.prod:2181,hub-zk-03.cloud-east.prod:2181"

    spoke :
        path : "/ebs/spoke"
        ttlMinutes : 60

conf/hazelcast.conf.xml :
    _template : hazelcast.conf.xml.jinja
    cluster_hosts :
        - "hub-v2-01.cloud-east.prod"
        - "hub-v2-02.cloud-east.prod"
        - "hub-v2-03.cloud-east.prod"

bin/start.sh :
  _template : start.sh.jinja
  max_heap : "1g"
  min_heap : "512m"
  min_new : "100m"
  environment : "prod"

bin/prestop.sh :
  _template : prestop.sh.jinja

conf/logback.xml :
    _template : logback.xml.jinja
    verbosity : "INFO"

lib/newrelic.yml :
  _template : newrelic.yml.jinja

