## This file holds the context data for the DEV environment to fill template files.
## The syntax is:
##
## relative/path/to/file :
##     _template: tplFile.jinja
##     parameter_name : parameter_value
##     parameter2 :
##         - item1
##         - item2
##
## The file should be in yaml syntax, with one top-level array for each template file.
## There should be a corresponding template file in triforce/tpl/ written in the Jinja templating language
## for each top-level item.
##
conf/hub.properties :
    _template : hub.properties.jinja
    backing :
        store : "aws"

    aws :
        protocol : "HTTP"
        environment : "staging"

    dynamo :
        endpoint : "dynamodb.us-east-1.amazonaws.com"
        table_creation_wait_minutes : 10

    graphite :
        hosts : "svcsmon.cloud-east.staging:2003"

    zookeeper :
        connection : "hub-01.cloud-east.staging:2181,hub-02.cloud-east.staging:2181,hub-03.cloud-east.staging:2181"


conf/hazelcast.conf.xml :
    _template : hazelcast.conf.xml.jinja
    cluster_hosts :
        - "hub-01.cloud-east.staging"
        - "hub-02.cloud-east.staging"
        - "hub-03.cloud-east.staging"

conf/zoo.cfg :
    _template : zoo.cfg.jinja
    dataDir : "/home/hub/hub/mnt/zookeeper/"
    dataLogDir : "/home/hub/hub/mnt/zookeeper/"
    server :
      1 : "hub-01.cloud-east.staging:2888:3888"
      2 : "hub-02.cloud-east.staging:2888:3888"
      3 : "hub-03.cloud-east.staging:2888:3888"

